travis:
  secure:
    BINSTAR_TOKEN: RZJyQESSYjeqWk2YwEXOQ7Pjwvk6RzBNDKxztHxdtIBJINNhPEF+TDHhLVzpbRQ3Wy6KMwbEvTQY8vCkphVEaTACBQV67oA5TvaEJ1d4eIxlwdpYsmpVlwS6/+f9ctRrFG0TK2q20/We6OSJJFoMTdqV/6JjqeugysRMnjNysfTBPmn9gnj1aL5pvdTfCuO8jywH1m8k5hqevGqK33YeUMY3SsAJJ21A9BRHFOfH+bqjrU8nl3Vt4PRAzUxapgLD8twQyqUV4lXXlcRsLMlcYAM5fOYcIqURVGJjkbXJDzd9UAZPuYb4bjBfw+0v+/GGAfPia9brLoBb8TK+ckDOtrCtK+WK5aMgwz3S/1b+1HpxfgyQJa4SOWTxJzR7HDzjLY7DNzJyU71EDcty3VUoNf7S9vrfC0A/UDrbnEfGReJnUmBNSYXvVYKcLhPVf2Xp1uttjgXsXhQo9rx6uMokOOZxqEUtN6EkvYYQSdGEl7lpW8nEQNPpE5SK4eAA8XAaPQYUHwpbv44BT/cpVzuLOs+qu0OoB1VS776TCyKEYopGdzR7DYHWzF8vgBY7YFCkBrnQzqhyJXCdv1FGoHcX3uz/mOQcHmh+SEd2jl+RUZs2wl33i7KOiZt1E9c0H+/QiyrNvD7YxJ5fE6rIx+Ta4KyQCYDsDrbhxBz3aUx5xyo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
